version: "3.7"

services:
    # image project
    app:
        container_name: biblio-api
        build: ./biblio-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./biblio-api:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./biblio-api:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # nginx
    nginx:
        # image: nginx:alpine
        build: ./nginx
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./biblio-api:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
